"use client";

import { useState } from "react";
import Link from "next/link";
import { useDatasets } from "@/features/datasets/hooks/useDatasets";
import { useDecisions } from "@/features/decision-making/hooks/useDecisions";
import { StrategicRecommendationCard } from "@/features/decision-making/components/StrategicRecommendationCard";
import { RiskMatrix } from "@/features/decision-making/components/RiskMatrix";
import { ImpactEffortMatrix } from "@/features/decision-making/components/ImpactEffortMatrix";
import { ROIPanel } from "@/features/decision-making/components/ROIPanel";
import { BusinessRequirementPanel } from "@/features/decision-making/components/BusinessRequirementPanel";
import { InsightsSkeleton } from "@/components/skeletons/InsightsSkeleton";
import { Button } from "@/components/ui/button";
import { DatasetPicker } from "@/components/shared/DatasetPicker";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import { ListChecks } from "lucide-react";

export default function DecisionMakingPage() {
  const { data: datasets } = useDatasets();
  const [selectedDatasetId, setSelectedDatasetId] = useState<string | null>(null);
  const datasetId = selectedDatasetId ?? datasets?.[0]?.id ?? null;
  const { data: decisions, isLoading } = useDecisions(datasetId ?? "");

  return (
    <div className="space-y-6 animate-fade-up">
      <div className="flex items-center justify-between">
        <DatasetPicker value={datasetId} onChange={setSelectedDatasetId} />
        <Link href="/decision-making/action-tracking">
          <Button variant="secondary" size="sm">
            <ListChecks className="h-3.5 w-3.5" /> Action tracking
          </Button>
        </Link>
      </div>

      {!datasetId ? (
        <p className="text-sm text-ink-faint">Upload a dataset to get started with decision recommendations.</p>
      ) : (
        <Tabs defaultValue="auto">
          <TabsList>
            <TabsTrigger value="auto">Auto-Generated</TabsTrigger>
            <TabsTrigger value="requirements">Business Requirements</TabsTrigger>
          </TabsList>

          <TabsContent value="auto">
            {isLoading || !decisions ? (
              <InsightsSkeleton />
            ) : (
              <div className="space-y-6">
                <p className="text-sm text-ink-muted">
                  {decisions.length} recommendations generated by the Decision Support agent
                </p>

                <div className="grid gap-4 lg:grid-cols-2">
                  <ROIPanel decisions={decisions} />
                  <RiskMatrix decisions={decisions} />
                </div>

                <ImpactEffortMatrix decisions={decisions} />

                <div>
                  <p className="eyebrow mb-3">Strategic Recommendations</p>
                  <div className="grid gap-4 md:grid-cols-2">
                    {decisions.map((d) => (
                      <StrategicRecommendationCard key={d.id} decision={d} />
                    ))}
                  </div>
                </div>
              </div>
            )}
          </TabsContent>

          <TabsContent value="requirements">
            <BusinessRequirementPanel datasetId={datasetId} />
          </TabsContent>
        </Tabs>
      )}
    </div>
  );
}
